config/routes.rb
Rails.application.routes.draw do

root :to => 'sessions#show'
  get 'sessions/new'

  post 'list/followers' => 'followers#create'
  post 'list/users' => 'users#create'
  post 'list/songs' => 'songs#create'
  post 'list/purchases' => 'purchases#create'
  post 'list/votes' => 'votes#create', :as => 'create_vote'
  post 'list/favorites' => 'favorites#create', :as => 'create_favorite'
  post 'list/genres' => 'genres#create'
  post 'list/song_types' => 'song_types#create'
  post 'list/purchased_informations' => 'purchased_informations#create'
  post 'destroy/favorite' => 'favorites#destroy'

  get 'logout' => 'sessions#destroy', :as => 'logout'
  get 'login' => 'sessions#new', :as => 'login'
  get 'search_song' => 'songs#search', :as => 'search_song'
  get 'search_user' => 'users#search', :as => 'search_user'
  get ':username' => 'users#show', :as => 'user_show'
  get 'user/:id' => 'users#show', :as => 'users_show'
  get ':username/edit' => 'users#edit', :as => 'user_edit'
  get 'account/:id' => 'users#edit', :as => 'account'
  get ':username/favorites' => 'favorites#userfav', :as => 'user_favorites'

  get 'list/users' => 'users#index', :as => 'users'
  get 'list/followers' => 'followers#index', :as => 'followers'
  get 'list/songs' => 'songs#index', :as => 'songs'
  get 'list/followers_new' => 'followers#new', :as => 'followers_new'
  get 'list/votes' => 'votes#index', :as => 'votes'
  get 'list/purchases' => 'purchases#index', :as => 'purchases'
  get 'list/favoritos' => 'favorites#index', :as => 'favorites'
  get 'list/genres' => 'genres#index', :as => 'genres'
  get 'list/song_types' => 'song_types#index', :as => 'song_types'
  get 'list/purchased_informations' => 'purchased_informations#index', :as => 'purchased_informations'

  post 'new_favorite' => 'favorites#resolve_layout'
  
  resources :report_types

  resources :purchased_informations

  resources :followers

  resources :song_types

  resources :purchases

  resources :votes

  resources :songs

  resources :users

  resources :favorites

  resources :reports

  resources :locations

  resources :reportables

  resources :genres

  resources :countries

  resources :admins

  resources :sessions

end

app/models/favorite.rb
class Favorite < ActiveRecord::Base
  # self.primary_keys = :user_id, :song_id 
  belongs_to :user
  belongs_to :song
end

app/controllers/favorites_controller.rb
class FavoritesController < ApplicationController
  before_action :set_favorite, only: [:show, :edit, :update]
  before_action :find_favorite, only: [:destroy]

  # GET /favorites
  # GET /favorites.json
  def index
    @favorites = Favorite.all
  end

  # GET /favorites/1
  # GET /favorites/1.json
  def show
  end

  # GET /favorites/new
  def new
    @favorite = Favorite.new
  end

  # GET /favorites/1/edit
  def edit
  end

  def userfav
    @favorites = Favorite.where(user_id:session[:user_id]).paginate(:page => params[:page], :per_page => 10);
  end

  # POST /favorites
  # POST /favorites.json
  def create
    @favorite = Favorite.new(favorite_params)

    respond_to do |format|
      if @favorite.save
        format.html { redirect_to :back, notice: 'Favorite was successfully created.' }
        format.json { render :show, status: :created, location: @favorite }
      else
        format.html { render :new }
        format.json { render json: @favorite.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /favorites/1
  # PATCH/PUT /favorites/1.json
  def update
    respond_to do |format|
      if @favorite.update(favorite_params)
        format.html { redirect_to @favorite, notice: 'Favorite was successfully updated.' }
        format.json { render :show, status: :ok, location: @favorite }
      else
        format.html { render :edit }
        format.json { render json: @favorite.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /favorites/1
  # DELETE /favorites/1.json
  def destroy

    #if params[:id]
     #@favorite = Favorite.find(params[:id])
    #else
      #@favorite = Favorite.all.where(user_id:favorite_params[:user_id], song_id:favorite_params[:song_id]).first
    #end

    @favorite.destroy
    respond_to do |format|
      format.html { redirect_to :back, notice: 'Favorite was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_favorite
      @favorite = Favorite.find(params[:id])
    end

    def find_favorite
      @favorite = Favorite.all.where(user_id: favorite_params[:user_id], song_id: favorite_params[:song_id]).first
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def favorite_params
      params.require(:favorite).permit(:id, :user_id, :song_id)
    end
end

app/helpers/favorites_helper.rb
module FavoritesHelper
end

app/views/favorites/_form.html.erb
<%= form_for(@favorite) do |f| %>
  <% if @favorite.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@favorite.errors.count, "error") %> prohibited this favorite from being saved:</h2>

      <ul>
      <% @favorite.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :user_id %><br>
    <%= f.text_field :user_id %>
  </div>
  <div class="field">
    <%= f.label :song_id %><br>
    <%= f.text_field :song_id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/favorites/edit.html.erb
<h1>Editing favorite</h1>

<%= render 'form' %>

<%= link_to 'Show', @favorite %> |
<%= link_to 'Back', favorites_path %>

app/views/favorites/index.html.erb
<h1>Listing favorites</h1>

<table>
  <thead>
    <tr>
      <th>Id</th>
      <th>User</th>
      <th>Song</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @favorites.each do |favorite| %>
      <tr>
        <td><%= favorite.id %></td>
        <td><%= favorite.user_id %></td>
        <td><%= favorite.song_id %></td>
        <td><%= link_to 'Show', favorite %></td>
        <td><%= link_to 'Edit', edit_favorite_path(favorite) %></td>
        <td><%= form_for :favorite, url: destroy_favorite_path, html: { id: "delete_favorite", style: "display:inline-block;" }, authenticity_token: form_authenticity_token do |f| %>
  
  <%= f.hidden_field  :user_id, { :value => favorite.user_id } %>
  <%= f.hidden_field  :song_id, { :value => favorite.song_id } %>

  <i class="fi-star favorite">
    <%= submit_tag nil %>
  </i>

<% end %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Favorite', new_favorite_path %>

app/views/favorites/new.html.erb
<h1>New favorite</h1>

<%= render 'form' %>

<%= link_to 'Back', :back %>

app/views/favorites/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>User:</strong>
  <%= @favorite.user %>
</p>

<p>
  <strong>Song:</strong>
  <%= @favorite.song %>
</p>

<%= link_to 'Edit', edit_favorite_path(@favorite) %> |
<%= link_to 'Back', :back %>

app/views/favorites/userfav.html.erb
<div class="content_header" style="margin: 5% 5%;">
	<h2 tabindex="0"><strong>Favorites
</div>

<div class="track_playlist" tab-index="0" style="padding-bottom:50px">
	<audio src="" type="mp3" preload="none" class="audio_track" data-track=""></audio>
	<% @favorites.each do |f|%>
		<% s = Song.find(f.song_id) %>
		<script>
			<% if session[:user_id] == s.user[:id] %>
				addTrack("<%= s.path %>","<%= s.name %>","<%= s.user[:name] %>",null);
			<% else %>
				addTrack("<%= s.path %>","<%= s.name %>","<%= s.user[:name] %>",{"startTime":<%= s.minMin %>,"endTime":<%= s.maxMin %>});
			<% end %>
		</script>
	<% end %>
</div>
<%= will_paginate @songs %>