config/routes.rb
Rails.application.routes.draw do

root :to => 'sessions#show'
  get 'sessions/new'

  post 'list/followers' => 'followers#create'
  post 'list/users' => 'users#create'
  post 'list/songs' => 'songs#create'
  post 'list/purchases' => 'purchases#create'
  post 'list/votes' => 'votes#create', :as => 'create_vote'
  post 'list/favorites' => 'favorites#create', :as => 'create_favorite'
  post 'list/genres' => 'genres#create'
  post 'list/song_types' => 'song_types#create'
  post 'list/purchased_informations' => 'purchased_informations#create'
  post 'destroy/favorite' => 'favorites#destroy'

  get 'logout' => 'sessions#destroy', :as => 'logout'
  get 'login' => 'sessions#new', :as => 'login'
  get 'search_song' => 'songs#search', :as => 'search_song'
  get 'search_user' => 'users#search', :as => 'search_user'
  get ':username' => 'users#show', :as => 'user_show'
  get 'user/:id' => 'users#show', :as => 'users_show'
  get ':username/edit' => 'users#edit', :as => 'user_edit'
  get 'account/:id' => 'users#edit', :as => 'account'
  get ':username/favorites' => 'favorites#userfav', :as => 'user_favorites'

  get 'list/users' => 'users#index', :as => 'users'
  get 'list/followers' => 'followers#index', :as => 'followers'
  get 'list/songs' => 'songs#index', :as => 'songs'
  get 'list/followers_new' => 'followers#new', :as => 'followers_new'
  get 'list/votes' => 'votes#index', :as => 'votes'
  get 'list/purchases' => 'purchases#index', :as => 'purchases'
  get 'list/favoritos' => 'favorites#index', :as => 'favorites'
  get 'list/genres' => 'genres#index', :as => 'genres'
  get 'list/song_types' => 'song_types#index', :as => 'song_types'
  get 'list/purchased_informations' => 'purchased_informations#index', :as => 'purchased_informations'

  post 'new_favorite' => 'favorites#resolve_layout'
  
  resources :report_types

  resources :purchased_informations

  resources :followers

  resources :song_types

  resources :purchases

  resources :votes

  resources :songs

  resources :users

  resources :favorites

  resources :reports

  resources :locations

  resources :reportables

  resources :genres

  resources :countries

  resources :admins

  resources :sessions

end

app/models/song.rb
class Song < ActiveRecord::Base
  mount_uploader :path, SongUploader
  mount_uploader :demo, AvatarUploader
  belongs_to :reportable
  belongs_to :user

  has_many :genres, through: :song_types
  has_many :users, through: :purchases
  has_many :users, through: :votes
  has_many :users, through: :favorites
  
  validates :name, presence: true

  validates :path, presence: true
  validates :price, presence: true, numericality: {greater_than_or_equal: 0.0}
  validates :minMin, presence: true
  validates :maxMin, presence: true
  #validates :genre, presence: true 
  validate :minimum_time_error
  #validate :maximum_time_error


  def minimum_time_error
    if maxMin - minMin > 30
      errors.add(:minMin, :maxMin, "Error")
    end
  end

  #def maximum_time_error
    #if maxMin - 30 > minMin
  #     errors.add("Error")
   #   end
 # end﻿
  
end

app/models/song_type.rb
class SongType < ActiveRecord::Base
  # self.primary_keys = :song_id, :genre_id
  belongs_to :song
  belongs_to :genre
end

app/controllers/songs_controller.rb
class SongsController < ApplicationController
  before_action :set_song, only: [:show, :edit, :update, :destroy]

  # GET /songs
  # GET /songs.json
  def index
    @songs = Song.all
    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @users}
    end
  end

  # GET /songs/1
  # GET /songs/1.json
  def show
  end

  # GET /songs/new
  def new
    @song = Song.new
  end

  # GET /songs/1/edit
  def edit
  end

  # POST /songs
  # POST /songs.json
  def create
    x = song_params
    user = User.find(session[:user_id])
    x[:user] = user
    @song = Song.create(x)

    respond_to do |format|
      if @song.save
        format.html { redirect_to user_show_path(user[:username]), notice: 'Song was successfully created.' } # temporario => alterar redirecionamento
        format.json { render :show, status: :created, location: @song }
      else
        format.html { render :new }
        format.json { render json: @song.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /songs/1
  # PATCH/PUT /songs/1.json
  def update
    respond_to do |format|
      if @song.update(song_params)
        format.html { redirect_to @song, notice: 'Song was successfully updated.' }
        format.json { render :show, status: :ok, location: @song }
      else
        format.html { render :edit }
        format.json { render json: @song.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /songs/1
  # DELETE /songs/1.json
  def destroy
    @status_update = Song.find(params[:id])
    if @status_update.present?
      @status_update.destroy
    end
    redirect_to songs_path
  end

  def search
    if song_params[:name] != "" && song_params[:price] != "" && song_params[:main_influence] != "" && song_params[:genre] != "Song genre"
      @search = Song.where("name LIKE :sname AND price = :sprice AND main_influence = :smain_influence AND genre = :sgenre", {:sname => "%#{song_params[:name]}%", :sprice => "#{song_params[:price]}", :smain_influence => "#{song_params[:main_influence]}", :sgenre => "#{song_params[:genre]}"})
    elsif song_params[:name] != "" && song_params[:price] == "" && song_params[:main_influence] == "" && song_params[:genre] == "Song genre"
      @search = Song.where("name LIKE :sname", {:sname => "%#{song_params[:name]}%"})
    elsif song_params[:name] == "" && song_params[:price] != "" && song_params[:main_influence] == "" && song_params[:genre] == "Song genre"
      @search = Song.where("price = :sprice", {:sprice => "#{song_params[:price]}"})
    elsif song_params[:name] == "" && song_params[:price] == "" && song_params[:main_influence] == "" && song_params[:genre] != "Song genre"
      @search = Song.where("genre = :sgenre", {:sgenre => "#{song_params[:genre]}"})
    elsif song_params[:name] == "" && song_params[:price] == "" && song_params[:main_influence] != "" && song_params[:genre] == "Song genre"
      @search = Song.where("main_influence = :smain_influence", {:smain_influence => "#{song_params[:main_influence]}"})
    elsif song_params[:name] != "" && song_params[:price] != "" && song_params[:main_influence] == "" && song_params[:genre] == "Song genre"
      @search = Song.where("name LIKE :sname AND price = :sprice", {:sname => "%#{song_params[:name]}%", :sprice => "#{song_params[:price]}"})
    elsif song_params[:name] != "" && song_params[:price] == "" && song_params[:main_influence] == "" && song_params[:genre] != "Song genre"
      @search = Song.where("name LIKE :sname AND genre = :sgenre", {:sname => "%#{song_params[:name]}%", :sgenre => "#{song_params[:genre]}"})
    elsif song_params[:name] != "" && song_params[:price] == "" && song_params[:main_influence] != "" && song_params[:genre] == "Song genre"
      @search = Song.where("name LIKE :sname AND main_influence = :smain_influence", {:sname => "%#{song_params[:name]}%", :smain_influence => "#{song_params[:main_influence]}"})
    elsif song_params[:name] == "" && song_params[:price] != "" && song_params[:main_influence] == "" && song_params[:genre] != "Song genre"
      @search = Song.where("price = :sprice AND genre = :sgenre", {:sprice => "#{song_params[:price]}", :sgenre => "#{song_params[:genre]}"})
    elsif song_params[:name] == "" && song_params[:price] != "" && song_params[:main_influence] != "" && song_params[:genre] == "Song genre"
      @search = Song.where("price = :sprice AND main_influence = :smain_influence", {:sprice => "#{song_params[:price]}", :smain_influence => "#{song_params[:main_influence]}"})
    elsif song_params[:name] == "" && song_params[:price] == "" && song_params[:main_influence] != "" && song_params[:genre] != "Song genre"
      @search = Song.where("genre = :sgenre AND main_influence = :smain_influence", {:sgenre => "#{song_params[:genre]}", :smain_influence => "#{song_params[:main_influence]}"})
    elsif song_params[:name] != "" && song_params[:price] != "" && song_params[:main_influence] != "" && song_params[:genre] == "Song genre"
      @search = Song.where("name LIKE :sname AND price = :sprice AND main_influence = :smain_influence", {:sname => "%#{song_params[:name]}%", :sprice => "#{song_params[:price]}", :smain_influence => "#{song_params[:main_influence]}"})
    elsif song_params[:name] != "" && song_params[:price] != "" && song_params[:main_influence] == "" && song_params[:genre] != "Song genre"
      @search = Song.where("name LIKE :sname AND price = :sprice AND genre = :sgenre", {:sname => "%#{song_params[:name]}%", :sprice => "#{song_params[:price]}", :sgenre => "#{song_params[:genre]}"})
    elsif song_params[:name] != "" && song_params[:price] == "" && song_params[:main_influence] != "" && song_params[:genre] != "Song genre"
      @search = Song.where("name LIKE :sname AND genre = :sgenre AND main_influence = :smain_influence", {:sname => "%#{song_params[:name]}%", :sgenre => "#{song_params[:genre]}", :smain_influence => "#{song_params[:main_influence]}"})
    elsif song_params[:name] == "" && song_params[:price] != "" && song_params[:main_influence] != "" && song_params[:genre] != "Song genre"
      @search = Song.where("genre = :sgenre AND price = :sprice AND main_influence = :smain_influence", {:sgenre => "#{song_params[:genre]}", :sprice => "#{song_params[:price]}", :smain_influence => "#{song_params[:main_influence]}"})
    end
  end

  

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_song
      @song = Song.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def song_params
      params.require(:song).permit(:user, :name, :minMin, :maxMin, :price, :path, :main_influence, :genre, :demo)
    end
end

app/helpers/songs_helper.rb
module SongsHelper
end

app/views/songs/_addGenre.html.erb
<div id="addGenreModal" class="reveal-modal" data-reveal style="padding:28px;min-height: 0;">
	<form accept-charset="UTF-8" action="/list/song_types" id="new_genre" method="post" style="display:inline-block;">
		<div style="display:none">
			<input name="utf8" type="hidden" value="✓">
			<input name="authenticity_token" type="hidden" value="<%= form_authenticity_token %>">
		</div>

		<select id="song_type_genre_id" name="song_type[genre_id]" style="display: inline-block;width: 190px;height: 13px;border-radius: 9px;margin: 0;">
			<% Genre.all.each do |g|%>
				<option value="<%= g.id %>"><%= g.name %></option>
			<% end %>
		</select>

		<input id="song_type_song_id" name="song_type[song_id]" type="hidden" value ="<%= @song.id %>">

		<p class="button submit"><input name="commit" type="submit" value="add"></p>

	</form>
</div>

app/views/songs/_dislikeform.html.erb
<%= form_for :vote, url: create_vote_path, html: { id: "new_vote", style: "display:inline-block;" }, authenticity_token: form_authenticity_token do |f| %>
  
  <%= f.hidden_field  :user_id, { :value => session[:user_id] } %>
  <%= f.hidden_field  :song_id, { :value => @song.id } %>
  <%= f.hidden_field :vote, { :value => "false" } %>

  <i class="fi-dislike favorite">
    <%= submit_tag nil %>
    <span><%= Vote.all.where(song_id:@song.id, vote:false).count %></span>
  </i>

<% end %>

app/views/songs/_favorite.html.erb
<!-- <form accept-charset="UTF-8" action="/list/favorites" id="new_favorite" method="post" style="display:inline-block;">
  <div style="display:none">
    <input name="utf8" type="hidden" value="✓">
    <input name="authenticity_token" type="hidden" value="<%= form_authenticity_token %>">
  </div>

  <input id="favorite_user_id" name="favorite[user_id]" type="hidden" value ="<%= session[:user_id] %>">
  <input id="favorite_song_id" name="favorite[song_id]" type="hidden" value ="<%= @song.id %>">

  <i class="fi-star favorite">
    <input name="commit" type="submit" style="position: absolute;width: 16px;height: 26px;right: 9px;top: 2px;opacity: 0;"> 
  </i> 
</form> -->

<%= form_for :favorite, url: create_favorite_path, html: { id: "new_favorite", style: "display:inline-block;" }, authenticity_token: form_authenticity_token do |f| %>
	
	<%= f.hidden_field	:user_id, { :value => session[:user_id] } %>
	<%= f.hidden_field	:song_id, { :value => @song.id } %>

	<i class="fi-star favorite">
		<%= submit_tag nil, style:"position: absolute;width: 16px;height: 26px;left: 182px;top: 17px;opacity: 0;" %>
	</i>

<% end %>

app/views/songs/_form.html.erb
<%= form_for(@song) do |f| %>
<% if @song.errors.any? %>
<div data-alert class="alert-box alert" id="error_explanation">

  <h3>Sorry... You made <%= pluralize(@song.errors.count, "mistake") %>:</h3>

  <ul>
    <% @song.errors.full_messages.each do |message| %>
    <li><%= message %></li>
    <% end %>
  </ul>

  <a href="#" class="close">&times;</a>
</div>
<% end %>

<form>
  <ul class="upload_info">
  <%= f.file_field :path %>
  <li>
    <i class="fi-music"></i>
    <%= f.text_field :name, :placeholder => "Name" %>
  </li>
  <li><i class="fi-price-tag"></i><i class="fi-euro" style="left: 80px;"></i>
    <%= f.number_field(:price, in: 0.01..10.0, step: 0.01, :placeholder => "Price") %>
  </li>
  <li>
    <i class="fi-play-video" style="top: 2;left: 200px;"></i>
    <%= f.number_field(:minMin, :min => 0.0, :placeholder => "Start") %>
    <i class="fi-play-video" style="top: 2;left: 200px;"></i>
    <%= f.number_field(:maxMin, :min => 0.0, :placeholder => "End") %>
    <div class="row field">
      <div class="large-9 columns">
        <%= f.label :demo %><br>
        <%= f.file_field :demo %>
      </div>
    </div>
    <div class="actions button large radius">
      <%= f.submit %>
    </div>
  </li>
</ul>
</form>
<% end %>

app/views/songs/_likeform.html.erb
<%= form_for :vote, url: create_vote_path, html: { id: "new_vote", style: "display:inline-block;" }, authenticity_token: form_authenticity_token do |f| %>
  
  <%= f.hidden_field  :user_id, { :value => session[:user_id] } %>
  <%= f.hidden_field  :song_id, { :value => @song.id } %>
  <%= f.hidden_field :vote, { :value => "true" } %>

  <i class="fi-like favorite">
    <%= submit_tag nil %>
    <span><%= Vote.all.where(song_id:@song.id, vote:true).count %></span>
  </i>

<% end %>

app/views/songs/_unfavorite.html.erb
<!-- <form accept-charset="UTF-8" action="/destroy/favorite" id="delete_favorite" method="post" style="display:inline-block">
  <div style="display:none">
    <input name="utf8" type="hidden" value="✓">
    <input name="authenticity_token" type="hidden" value="<%= form_authenticity_token %>">
  </div>

  <input id="favorite_user_id" name="favorite[user_id]" type="hidden" value ="<%= session[:user_id] %>">
  <input id="favorite_song_id" name="favorite[song_id]" type="hidden" value ="<%= @song.id %>">
  <i class="fi-star unfavorite">
    <input name="commit" type="submit" style="position: absolute;width: 16px;height: 26px;right: 9px;top: 2px;opacity: 0;"> 
  </i> 
</form> -->

<%= form_for :favorite, url: destroy_favorite_path, html: { id: "delete_favorite", style: "display:inline-block;" }, authenticity_token: form_authenticity_token do |f| %>
	
	<%= f.hidden_field	:user_id, { :value => session[:user_id] } %>
	<%= f.hidden_field	:song_id, { :value => @song.id } %>

	<i class="fi-star unfavorite">
		<%= submit_tag nil, class: "favorite-button", style:"position: absolute;width: 16px;height: 26px;left: 182px;top: 17px;opacity: 0;" %>
	</i>

<% end %>

app/views/songs/edit.html.erb
<h1>Editing song</h1>

<%= render 'form' %>

<%= link_to 'Show', @song %> |
<%= link_to 'Back', songs_path %>

app/views/songs/index.html.erb
<h1>Listing songs</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Minmin</th>
      <th>Maxmin</th>
      <th>Price</th>
      <th>PathSong</th>
      <th>PathImg</th>
      <th>User</th>
      <th>Main Genre</th>
      <th>Main Influence</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @songs.each do |song| %>
      <tr>
        <td><%= song.name %></td>
        <td><%= song.minMin %></td>
        <td><%= song.maxMin %></td>
        <td><%= song.price %></td>
        <td><%= song.path %></td>
        <td><%= song.demo %></td>
        <td><%= song.user_id %></td>
        <td><%= song.genre %></td>
        <td><%= song.main_influence %></td>
        <td><%= link_to 'Show', song %></td>
        <td><%= link_to 'Edit', edit_song_path(song) %></td>
        <td><%= link_to 'Destroy', song, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Song', new_song_path %>

app/views/songs/new.html.erb
<h1>New song</h1>

<%= render 'form' %>

<%= link_to 'Back', songs_path %>

app/views/songs/purchaseform.html.erb
<div id="myPurchase" class="reveal-modal" data-reveal>
  <h2>Awesome. I have it.</h2>
  <a class="close-reveal-modal">&#215;</a>
</div>

app/views/songs/search.html.erb
<div class="track_playlist">
  <audio src="" type="mp3" preload="none" class="audio_track" data-track=""></audio>
</div>
<% if @search.count > 0 %>
	<% @search.each do |s| %>
	<script>
  		addTrack("<%= s.path %>","<%= s.name %>","<%= s.user[:name] %>",{"startTime":<%= s.minMin %>,"endTime":<%= s.maxMin %>});
	</script>
	<% end %>
<% else %>
	<div id="no_search_song" data-alert class="alert-box alert round">
	  	<strong>No results found. Try other search.</strong>
	</div>
<% end %>
<%= link_to 'Back to profile', user_path(session['user_id']), :id => "bsb" %>

app/views/songs/show.html.erb
<div id="notice"><%= notice %></div>
<div id="Tsunami_0_modal">
	<div class="song_info_banner">
		<div class="popularity">
						<%= render "likeform" %>
						<%= render "dislikeform" %>
						<% if Favorite.where(user_id: session[:user_id], song_id: @song.id).blank? %>
						<%= render 'favorite' %>
						<% else %>
						<%= render 'unfavorite' %>
						<% end %>
					</div>
	</div>
	<div style="position: relative;bottom: 94px;">
		<div class="song_info_body">
			<div class="song_image_body">
					<%= image_tag(@song.demo, style:"width:175px;height: 175px;") %>
				<div class="add_to_playlist">
					<a data-dropdown="myplaylists" aria-controls="myplaylists" aria-expanded="false">
						<i class="fi-plus"></i>
					</a>
					<ul id="myplaylists" class="f-dropdown" data-dropdown-content aria-hidden="true" tabindex="-1">
						<li><a>Playlist 1</a></li>
						<li><a>Playlist 2</a></li>
						<li><a>Playlist 3</a></li>
						<hr style="margin: 0;">
						<!--li><a href="#" data-reveal-id="myModal">New Playlist</a></li-->
					</ul>
					<div id="myModal" class="reveal-modal" data-reveal>
						<h2>Create new playlist</h2>
						<hr>
						<p class="lead">Name</p>
						<input type="text">
						<a class="close-reveal-modal">&#215;</a>
					</div>
				</div>
				<div class="purchases_info">
					<div class="statistics">
						<span class="num_purchases">0</span>
						<span>&nbspPurchasers</span>
					</div>
					<% if @song.user[:id] != session[:user_id] %>
					<div class="buy">
						<a data-reveal-id="myPurchase">
							<i class="fi-shopping-cart"></i>
							<span class="">Purchase</span>
						</a>
						<%= render "purchases/form" %>
					</div>
					<% end %>
				</div>
			</div>
			<div class="song_main_info">
				<span class="name">
					<%= @song.name%>
					<% if @song.user[:id] == session[:user_id] %>
					<%= link_to "", edit_song_path(@song), class:"fi-pencil", style:"position: relative;font-size: 21px;bottom: 25px;color: black;right: 9px;text-shadow: none;"%>
					<%= link_to "", @song, method: :delete, data: { confirm: 'Are you sure?' }, class:"fi-x", style:"position: relative;font-size: 21px;bottom: 25px;color: black;right: 9px;text-shadow: none;"%>
					<% end %>
				</span>
				<% if (PurchasedInformation.where(buyer:session[:user_id],seller:@song.user[:id]).first or session[:user_id] == @song.user[:id]) %>
					<a href="/<%= @song.user[:username] %>"><span class="artist"><%= @song.user[:name]%></span></a>
				<% else %>
					<a href="/user/<%= @song.user[:id] %>"><span class="artist">Unknown</span></a>
				<% end %>
				<div class="text_field">
					<%= @song.description %>
				</div>
				<div class="genres_info">
					<ul>
						<% SongType.all.where(song_id:@song.id).each do |st|%>
						<li><span class="genre"><%= st.genre.name %></span><a class="remove_genre"><i class="fi-x"></i></a></li>
						<% end %>
						<% if @song.user[:id] == session[:user_id] %>
						<li><a data-reveal-id="addGenreModal"><span class="genre" style="box-shadow: 0px 0px 7px 1px black;">Add +</span></a></li>
						<% end %>
					</ul>

				</div>
			</div>
		</div>
		<div class="price_tag" style="position: absolute;top: 0px;left: 193px;">
			<span class="fi-price-tag"><%= image_tag("cordel.png") %></span>
			<div class="price"><%= @song.price %>€</div>											
		</div>
	</div>
</div>

<div style="padding: 7px;background: white;border-top: 1px solid #D4D4D4;border-left: 1px solid #B3B3B3border-right: 1px solid #B3B3B3border-bottom: 1px solid #BDBDBD;-moz-box-shadow: 0 1px 10px -1px #D9D9D9;-webkit-box-shadow: 0 1px 10px -1px #D9D9D9;box-shadow: 0 1px 10px -1px #D9D9D9;width: 101%;right: 1%;position: relative;margin-bottom: 12px;">
	<div class="playlist_border">
		<div class="track_playlist">
			<audio src="" type="mp3" preload="none" class="audio_track" data-track=""></audio>
		</div>
	</div>
</div>

<%= render "addGenre" %>

<script>
	function opacity(element_id){
		if($("#"+element_id).text() == "")
			$("#"+element_id).css("opacity","0");
	}

	<% if session[:user_id] == @song.user[:id] %>
	addTrack("<%= @song.path %>","<%= @song.name %>","<%= @song.user[:name] %>",null);
	<% else %>
	addTrack("<%= @song.path %>","<%= @song.name %>","<%= @song.user[:name] %>",{"startTime":<%= @song.minMin %>,"endTime":<%= @song.maxMin %>});
	<% end %>
	opacity('notice');
</script>

<style type="text/css">
	.genres_info ul li:hover .remove_genre{
		display: inline-block;
	}
	.remove_genre{
		position: relative;
		bottom: 9px;
		right: 6px;
		width: 0;
		display: none;
	}
	.remove_genre i{
		display: flex;
	}
</style>