config/routes.rb
Rails.application.routes.draw do

root :to => 'sessions#show'
  get 'sessions/new'

  post 'list/followers' => 'followers#create'
  post 'list/users' => 'users#create'
  post 'list/songs' => 'songs#create'
  post 'list/purchases' => 'purchases#create'
  post 'list/votes' => 'votes#create', :as => 'create_vote'
  post 'list/favorites' => 'favorites#create', :as => 'create_favorite'
  post 'list/genres' => 'genres#create'
  post 'list/song_types' => 'song_types#create'
  post 'list/purchased_informations' => 'purchased_informations#create'
  post 'destroy/favorite' => 'favorites#destroy'

  get 'logout' => 'sessions#destroy', :as => 'logout'
  get 'login' => 'sessions#new', :as => 'login'
  get 'search_song' => 'songs#search', :as => 'search_song'
  get 'search_user' => 'users#search', :as => 'search_user'
  get ':username' => 'users#show', :as => 'user_show'
  get 'user/:id' => 'users#show', :as => 'users_show'
  get ':username/edit' => 'users#edit', :as => 'user_edit'
  get 'account/:id' => 'users#edit', :as => 'account'
  get ':username/favorites' => 'favorites#userfav', :as => 'user_favorites'

  get 'list/users' => 'users#index', :as => 'users'
  get 'list/followers' => 'followers#index', :as => 'followers'
  get 'list/songs' => 'songs#index', :as => 'songs'
  get 'list/followers_new' => 'followers#new', :as => 'followers_new'
  get 'list/votes' => 'votes#index', :as => 'votes'
  get 'list/purchases' => 'purchases#index', :as => 'purchases'
  get 'list/favoritos' => 'favorites#index', :as => 'favorites'
  get 'list/genres' => 'genres#index', :as => 'genres'
  get 'list/song_types' => 'song_types#index', :as => 'song_types'
  get 'list/purchased_informations' => 'purchased_informations#index', :as => 'purchased_informations'

  post 'new_favorite' => 'favorites#resolve_layout'
  
  resources :report_types

  resources :purchased_informations

  resources :followers

  resources :song_types

  resources :purchases

  resources :votes

  resources :songs

  resources :users

  resources :favorites

  resources :reports

  resources :locations

  resources :reportables

  resources :genres

  resources :countries

  resources :admins

  resources :sessions

end

app/models/follower.rb
class Follower < ActiveRecord::Base
	belongs_to :user, foreign_key: "follower_id"
	belongs_to :user, foreign_key: "followed_id"
end

app/controllers/followers_controller.rb
class FollowersController < ApplicationController
  before_action :set_follower, only: [:show, :edit, :update, :destroy]

  # GET /followers
  # GET /followers.json
  def index
    @followers = Follower.all
  end

  # GET /followers/1
  # GET /followers/1.json
  def show
  end

  # GET /followers/new
  def new
    @follower = Follower.new
  end

  # GET /followers/1/edit
  def edit
  end

  # POST /followers
  # POST /followers.json
  def create
      @follower = Follower.new(follower_params)

      respond_to do |format|
        if @follower.save
          format.html { redirect_to user_show_path(User.find(follower_params[:followed]).username) , notice: 'Follower was successfully created.' }
          format.json { render :show, status: :created, location: @follower }
        else
          format.html { render :new }
          format.json { render json: @follower.errors, status: :unprocessable_entity }
        end
    end
  end

  # PATCH/PUT /followers/1
  # PATCH/PUT /followers/1.json
  def update
    respond_to do |format|
      if @follower.update(follower_params)
        format.html { redirect_to @follower, notice: 'Follower was successfully updated.' }
        format.json { render :show, status: :ok, location: @follower }
      else
        format.html { render :edit }
        format.json { render json: @follower.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /followers/1
  # DELETE /followers/1.json
  def destroy
    username = User.find(@follower[:followed]).username
    @follower.destroy
    respond_to do |format|
      format.html { redirect_to user_show_path(username), notice: 'Follower was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_follower
      @follower = Follower.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def follower_params
      params.require(:follower).permit(:follower, :followed)
    end
end

app/helpers/followers_helper.rb
module FollowersHelper
end

app/views/followers/_form.html.erb
<%= form_for(@follower) do |f| %>
  <% if @follower.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@follower.errors.count, "error") %> prohibited this follower from being saved:</h2>

      <ul>
      <% @follower.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :follower %><br>
    <%= f.number_field :follower %>
  </div>
  <div class="field">
    <%= f.label :followed %><br>
    <%= f.number_field :followed %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/followers/edit.html.erb
<h1>Editing follower</h1>

<%= render 'form' %>

<%= link_to 'Show', @follower %> |
<%= link_to 'Back', followers_path %>

app/views/followers/index.html.erb
<h1>Listing followers</h1>

<table>
  <thead>
    <tr>
      <th>Follower</th>
      <th>Followed</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @followers.each do |follower| %>
      <tr>
        <td><%= follower.follower %></td>
        <td><%= follower.followed %></td>
        <td><%= link_to 'Show', follower %></td>
        <td><%= link_to 'Edit', edit_follower_path(follower) %></td>
        <td><%= link_to 'Destroy', follower, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Follower', new_follower_path %>

app/views/followers/new.html.erb
<h1>New follower</h1>

<%= render 'form' %>

<%= link_to 'Back', followers_path %>

app/views/followers/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Follower:</strong>
  <%= @follower.follower %>
</p>

<p>
  <strong>Followed:</strong>
  <%= @follower.followed %>
</p>

<%= link_to 'Edit', edit_follower_path(@follower) %> |
<%= link_to 'Back', followers_path %>