config/routes.rb
Rails.application.routes.draw do

root :to => 'sessions#show'
  get 'sessions/new'

  post 'list/followers' => 'followers#create'
  post 'list/users' => 'users#create'
  post 'list/songs' => 'songs#create'
  post 'list/purchases' => 'purchases#create'
  post 'list/votes' => 'votes#create', :as => 'create_vote'
  post 'list/favorites' => 'favorites#create', :as => 'create_favorite'
  post 'list/genres' => 'genres#create'
  post 'list/song_types' => 'song_types#create'
  post 'list/purchased_informations' => 'purchased_informations#create'
  post 'destroy/favorite' => 'favorites#destroy'

  get 'logout' => 'sessions#destroy', :as => 'logout'
  get 'login' => 'sessions#new', :as => 'login'
  get 'search_song' => 'songs#search', :as => 'search_song'
  get 'search_user' => 'users#search', :as => 'search_user'
  get ':username' => 'users#show', :as => 'user_show'
  get 'user/:id' => 'users#show', :as => 'users_show'
  get ':username/edit' => 'users#edit', :as => 'user_edit'
  get 'account/:id' => 'users#edit', :as => 'account'
  get ':username/favorites' => 'favorites#userfav', :as => 'user_favorites'

  get 'list/users' => 'users#index', :as => 'users'
  get 'list/followers' => 'followers#index', :as => 'followers'
  get 'list/songs' => 'songs#index', :as => 'songs'
  get 'list/followers_new' => 'followers#new', :as => 'followers_new'
  get 'list/votes' => 'votes#index', :as => 'votes'
  get 'list/purchases' => 'purchases#index', :as => 'purchases'
  get 'list/favoritos' => 'favorites#index', :as => 'favorites'
  get 'list/genres' => 'genres#index', :as => 'genres'
  get 'list/song_types' => 'song_types#index', :as => 'song_types'
  get 'list/purchased_informations' => 'purchased_informations#index', :as => 'purchased_informations'

  post 'new_favorite' => 'favorites#resolve_layout'
  
  resources :report_types

  resources :purchased_informations

  resources :followers

  resources :song_types

  resources :purchases

  resources :votes

  resources :songs

  resources :users

  resources :favorites

  resources :reports

  resources :locations

  resources :reportables

  resources :genres

  resources :countries

  resources :admins

  resources :sessions

end

app/models/report.rb
class Report < ActiveRecord::Base
  belongs_to :reportable
  belongs_to :admin
  belongs_to :report_type

  validates :reason, presence: true
end

app/models/report_type.rb
class ReportType < ActiveRecord::Base
	has_many :reports

	validates :tag, presence: true
end

app/controllers/reports_controller.rb
class ReportsController < ApplicationController
  before_action :set_report, only: [:show, :edit, :update, :destroy]

  # GET /reports
  # GET /reports.json
  def index
    @reports = Report.all
  end

  # GET /reports/1
  # GET /reports/1.json
  def show
  end

  # GET /reports/new
  def new
    @report = Report.new
  end

  # GET /reports/1/edit
  def edit
  end

  # POST /reports
  # POST /reports.json
  def create
    @report = Report.new(report_params)

    respond_to do |format|
      if @report.save
        format.html { redirect_to @report, notice: 'Report was successfully created.' }
        format.json { render :show, status: :created, location: @report }
      else
        format.html { render :new }
        format.json { render json: @report.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /reports/1
  # PATCH/PUT /reports/1.json
  def update
    respond_to do |format|
      if @report.update(report_params)
        format.html { redirect_to @report, notice: 'Report was successfully updated.' }
        format.json { render :show, status: :ok, location: @report }
      else
        format.html { render :edit }
        format.json { render json: @report.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /reports/1
  # DELETE /reports/1.json
  def destroy
    @report.destroy
    respond_to do |format|
      format.html { redirect_to reports_url, notice: 'Report was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_report
      @report = Report.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def report_params
      params.require(:report).permit(:reason, :checked, :reportable_id, :admin_id)
    end
end

app/helpers/reports_helper.rb
module ReportsHelper
end

app/views/reports/_form.html.erb
<%= form_for(@report) do |f| %>
  <% if @report.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@report.errors.count, "error") %> prohibited this report from being saved:</h2>

      <ul>
      <% @report.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :reason %><br>
    <%= f.text_field :reason %>
  </div>
  <div class="field">
    <%= f.label :checked %><br>
    <%= f.check_box :checked %>
  </div>
  <div class="field">
    <%= f.label :reportable_id %><br>
    <%= f.text_field :reportable_id %>
  </div>
  <div class="field">
    <%= f.label :admin_id %><br>
    <%= f.text_field :admin_id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/reports/edit.html.erb
<h1>Editing report</h1>

<%= render 'form' %>

<%= link_to 'Show', @report %> |
<%= link_to 'Back', reports_path %>

app/views/reports/index.html.erb
<h1>Listing reports</h1>

<table>
  <thead>
    <tr>
      <th>Reason</th>
      <th>Checked</th>
      <th>Reportable</th>
      <th>Admin</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @reports.each do |report| %>
      <tr>
        <td><%= report.reason %></td>
        <td><%= report.checked %></td>
        <td><%= report.reportable %></td>
        <td><%= report.admin %></td>
        <td><%= link_to 'Show', report %></td>
        <td><%= link_to 'Edit', edit_report_path(report) %></td>
        <td><%= link_to 'Destroy', report, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Report', new_report_path %>

app/views/reports/new.html.erb
<h1>New report</h1>

<%= render 'form' %>

<%= link_to 'Back', reports_path %>

app/views/reports/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Reason:</strong>
  <%= @report.reason %>
</p>

<p>
  <strong>Checked:</strong>
  <%= @report.checked %>
</p>

<p>
  <strong>Reportable:</strong>
  <%= @report.reportable %>
</p>

<p>
  <strong>Admin:</strong>
  <%= @report.admin %>
</p>

<%= link_to 'Edit', edit_report_path(@report) %> |
<%= link_to 'Back', reports_path %>